# Generated by Django 3.2.9 on 2021-12-14 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0002_auto_20211214_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movieinfo',
            name='category',
            field=models.CharField(choices=[('A', 'ACCION'), ('S', 'SUSPENSO'), ('C', 'SCIFI'), ('R', 'ROMANCE')], max_length=1),
        ),
    ]
