# Generated by Django 3.2.9 on 2021-12-14 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0003_alter_movieinfo_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movieinfo',
            name='category',
            field=models.CharField(choices=[('A', 'ACCION'), ('S', 'SUSPENSO'), ('S', 'SCIFI'), ('R', 'ROMANCE')], max_length=1),
        ),
    ]
