# Generated by Django 3.2.9 on 2021-12-15 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0006_auto_20211215_1505'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movieinfo',
            name='imagen',
        ),
    ]
