# Generated by Django 3.2.9 on 2021-12-15 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0007_remove_movieinfo_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='movieinfo',
            name='imagen',
            field=models.ImageField(default=0, upload_to='movies'),
            preserve_default=False,
        ),
    ]
