# Generated by Django 3.2.9 on 2021-12-15 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0009_remove_movieinfo_imagen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movieinfo',
            old_name='categiria',
            new_name='categoria',
        ),
    ]
