# Generated by Django 3.2.9 on 2021-12-15 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0010_rename_categiria_movieinfo_categoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movielinks',
            name='peli',
        ),
    ]
